---
- name: Ensure Nginx is configured
  include_role:
    name: nginx
    allow_duplicates: False

- name: Install dhparam.pem
  copy:
    src: dhparam.pem
    dest: /etc/nginx/dhparam.pem
    owner: root
    group: root
    mode: 0644
    force: no
  when: use_ssl

- name: Create folder for external nginx locations
  file:
    path: /etc/nginx/locations.d/{{ site.urls | first }}
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install site descriptor
  template:
    src: base-site.conf
    dest: /etc/nginx/sites-available/{{ site.name }}.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Enable site
  file:
    src: ../sites-available/{{ site.name }}.conf
    dest: /etc/nginx/sites-enabled/{{ site.name }}.conf
    state: link
  notify:
    - nginx

- name: Install firewall rules for resolvers
  template:
    src: roles/nginx/templates/resolvers.rules
    dest: /etc/iptables.d/nginx-resolvers.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Install firewall v6 rules for resolvers
  template:
    src: roles/nginx/templates/resolvers.6rules
    dest: /etc/ip6tables.d/nginx-resolvers.6rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables
